trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: TerrafomValidate
  jobs:
    - job: TerraformValidateJob
      steps:
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: 'System.DefaultWorkingDirectory)/terraform-manifests'
          artifact: 'terraform-manifests-out'
          publishLocation: 'pipeline'
      - task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@0
        inputs:
          terraformVersion: 'latest'
      - task: TerraformCLI@0
        inputs:
          command: 'init'
          workingDirectory: 'System.DefaultWorkingDirectory)/terraform-manifests'
          backendType: 'azurerm'
          backendServiceArm: 'terraform-azure-aks-sc'
          ensureBackend: true
          allowTelemetryCollection: false
      - task: TerraformCLI@0
        inputs:
          command: 'validate'
          workingDirectory: 'System.DefaultWorkingDirectory)/terraform-manifests'
          allowTelemetryCollection: false